version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: limbas
      POSTGRES_USER: limbas

  app:
    image: deuxm/limbas
    ports:
      - 8083:80
    links:
      - db
    restart: always
